name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - mlflow=2.8.0
  - ipython=8.16.1
  - notebook=7.0.6
  - jupyter=1.0.0
  - cookiecutter=2.4.0
  - hydra-core=1.3.2
  - matplotlib=3.8.1
  - pandas=2.1.2
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - protobuf==3.20.1