name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.2
  - pip=23.3.1
  - requests
  - mlflow=2.8.0
  - scikit-learn
  - pip:
      - wandb==0.16.0
      - git+https://github.com/weilerv/ML_Devops_project_2.git#egg=wandb-utils&subdirectory=components
