name: components
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - mlflow=2.8.0
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - scikit-learn=1.3.2
  - pip:
      - wandb==0.16.0