name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.2
  - pip=23.3.1
  - mlflow=2.8.0
  - scikit-learn=1.3.2
  - pip:
      - wandb==0.16.0
      - git+https://github.com/weilerv/ML_Devops_project_2.git#egg=wandb-utils&subdirectory=components
      - protobuf==3.20.*