name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.2
  - pip=23.3.1
  - mlflow=2.8.0
  - scikit-learn=1.3.2
  - matplotlib
  - pillow
  - pip:
      - wandb==0.16.0
